name: Java CI/CD Pipeline

on:
  push:
    branches: [test-main]
  pull_request:
    branches: [test-main]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: test-main

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Static Code Analysis with Checkstyle
        run: mvn checkstyle:checkstyle --file config-server/pom.xml

      - name: Upload Checkstyle Results
        uses: actions/upload-artifact@v2
        with:
          name: checkstyle-results
          path: config-server/target/checkstyle-result.xml

  build:
    runs-on: ubuntu-latest
    needs: static-analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: test-main

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file config-server/pom.xml -DskipTests=true
