name: Java CI/CD Pipeline

on:
  push:
    branches: [test-main]
  pull_request:
    branches: [test-main]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: test-main

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Static Code Analysis with Checkstyle
        run: mvn checkstyle:checkstyle --file microservice-commandes/pom.xml

      - name: Upload Checkstyle Results
        uses: actions/upload-artifact@v2
        with:
          name: checkstyle-results
          path: microservice-commandes/target/checkstyle-result.xml

  run_unit_tests:
    runs-on: ubuntu-latest
    needs: static-analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: test-main

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run unit tests
        run: mvn -B test -Dtest=CommandeControllerTest --file microservice-commandes/pom.xml

  run_integration_tests:
    runs-on: ubuntu-latest
    needs: static-analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: test-main

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run integration tests
        run: mvn -B test -Dtest=MicroserviceCommandesIT --file microservice-commandes/pom.xml

  build:
    runs-on: ubuntu-latest
    needs: [run_unit_tests, run_integration_tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: test-main

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file microservice-commandes/pom.xml -DskipTests=true
