name: Build Workflow

permissions:
  pull-requests: write
  contents: write

on:
  push:
    tags:
        - '*'

jobs:
  retrieve_tag:
    runs-on: ubuntu-latest
    outputs:
      previous-tag: ${{ steps.previoustag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
  bump_version:
    needs: retrieve_tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update pom files
        run: |
          mvn --batch-mode release:update-versions -DautoVersionSubmodules=true -DdevelopmentVersion=${{ needs.retrieve_tag.outputs.previous-tag }}-SNAPSHOT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: 'master'

