name: Reusable Bump Version Workflow

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  bump_version:
    needs: build_${{ inputs.project }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump Version
        id: bump
        uses: nnichols/maven-version-bump-action@v3
        with:
          pom-path: ./${{ inputs.project }}/pom.xml
          github-token: ${{ secrets.github_token }}}
